"""Rectilinear stills from referenced original GLB textures; no source writes.

Camera uses negative panorama bearing for Three yaw, positive up pitch, vertical
FOV. The existing inward sphere's Y rotation and flipped V make source longitude
equal to bearing. One source decode at a time bounds CPU/RAM usage.
"""
import io, json, math, struct, subprocess, sys, hashlib
from pathlib import Path
import numpy as np
from PIL import Image

root=Path(sys.argv[1]); plan=json.load(sys.stdin)
repo=root.parent.parent
def source_bytes(item):
    file=root/'assets'/item['source']['file']
    if file.exists(): return file.read_bytes()
    return subprocess.check_output(['git','show','HEAD:M7A_GitHub_Website_Full_Resolution/m7a-building/assets/'+item['source']['file']],cwd=repo)
def texture(data):
    if data[:4]!=b'glTF': raise ValueError('Not a GLB')
    size=struct.unpack_from('<I',data,12)[0]; doc=json.loads(data[20:20+size]); offset=20+size
    binary=data[offset+8:]
    material=doc['materials'][0]['pbrMetallicRoughness']['baseColorTexture']['index']
    image=doc['images'][doc['textures'][material]['source']]
    view=doc['bufferViews'][image['bufferView']]; begin=view.get('byteOffset',0)
    return Image.open(io.BytesIO(binary[begin:begin+view['byteLength']])).convert('RGB')
def capture(image,item):
    w,h=item['width'],item['height']; t=math.tan(math.radians(item['fov'])/2)
    xx,yy=np.meshgrid(((np.arange(w)+.5)/w*2-1)*t*w/h,(1-(np.arange(h)+.5)/h*2)*t)
    zz=np.ones_like(xx); pitch=item['pitch']; y=yy*math.cos(pitch)+zz*math.sin(pitch); z=zz*math.cos(pitch)-yy*math.sin(pitch)
    longitude=-item['yaw']+np.arctan2(xx,z); latitude=np.arctan2(y,np.sqrt(xx*xx+z*z))
    iw,ih=image.size; u=(longitude/(2*math.pi)%1)*iw-.5; v=np.clip((.5-latitude/math.pi)*ih-.5,0,ih-1)
    x0=np.floor(u).astype(int);y0=np.floor(v).astype(int); fx=(u-x0)[...,None];fy=(v-y0)[...,None]
    pixels=np.asarray(image);x1=(x0+1)%iw;x0%=iw;y1=np.minimum(y0+1,ih-1)
    out=(pixels[y0,x0]*(1-fx)*(1-fy)+pixels[y0,x1]*fx*(1-fy)+pixels[y1,x0]*(1-fx)*fy+pixels[y1,x1]*fx*fy)
    return Image.fromarray(np.round(out).astype('uint8'))
generated=0;reused=0
for item in plan:
    output=root/item['path'][2:];output.parent.mkdir(exist_ok=True)
    keep=item.pop('keepCapture',False)
    if item['reused']:
        if not output.exists():
            output.write_bytes(subprocess.check_output(['git','show','HEAD:M7A_GitHub_Website_Full_Resolution/m7a-building/'+item['path'][2:]],cwd=repo))
        reused+=1
    elif not keep:
        data=source_bytes(item);item['sourceSha256']=hashlib.sha256(data).hexdigest()
        with texture(data) as image:
            item['sourceDimensions']=list(image.size)
            capture(image,item).save(output,quality=84,optimize=True,progressive=True)
        generated+=1
    item['bytes']=output.stat().st_size
    item['imageRevision']=hashlib.sha256(output.read_bytes()).hexdigest()[:16]
    print(item['sceneId'],item['source']['file'],item['path'],flush=True)
manifest={item['sceneId']:item for item in plan}
(root/'scene-previews.generated.js').write_text('// Generated by scripts/build-scene-previews.cjs; source panoramas unchanged.\nexport const SCENE_PREVIEWS='+json.dumps(manifest,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'Generated {generated}; reused {reused}; coverage {len(manifest)}')
